name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild build \
            -project PlackoApp/PlackoApp.xcodeproj \
            -scheme PlackoApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15'
